import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AddressProvider } from '../context/AddressContext';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AddressProvider>
          {children}
        </AddressProvider>
      </body>
    </html>
  );
}
